version:  '2.1'

services:
  go_user:
    container_name: go_user
    build: .
    ports:
      - 8000:8000
    depends_on:
      mysql_user:
        condition: service_healthy

  mysql_user:
    container_name: mysql_user
    image: mysql:5.7
    restart: on-failure
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user
    volumes:
      - ./db/user:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

