version: '3.9'

services:
  go_user:
    container_name: go_user
    build: .
    ports:
      - 8080:8080
    depends_on:
      mysql_user:
        condition: service_healthy
    entrypoint: ["/bin/server" ,"-port=:8080" ,"-dsn=root:password@tcp(mysql_user:3306)/user", "-key=your_jwt_key"]
    networks:
      - backend

  mysql_user:
    container_name: mysql_user
    image: mysql:8.0
    restart: on-failure
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user
    volumes:
      - ./db/user:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    networks:
      - backend

networks:
  backend:
    name: tasks_ms